set_alarm:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: qingping_cgd1
          multiple: true
    slot:
      required: true
      selector:
        number:
          min: 0
          max: 15
          mode: box
    time:
      required: true
      selector:
        time:
    days:
      selector:
        select:
          multiple: true
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
    snooze:
      selector:
        boolean:
    enabled:
      selector:
        boolean:

delete_alarm:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: qingping_cgd1
          multiple: true
    slot:
      required: true
      selector:
        number:
          min: 0
          max: 15
          mode: box

sync_time:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: qingping_cgd1
          multiple: true
